version: '3'

tasks:
  run:
    desc: "Run the auth-svc service"
    cmds:
      - "go run cmd/main.go"

  proto:
    desc: "Generate the proto files"
    cmds:
      - "protoc --go_out=internal/pb --go-grpc_out=internal/pb internal/pb/*.proto"

  test:
    desc: "Run the tests"
    cmds:
      - "go test -v ./..."